import React, { createContext, useContext, useState } from 'react';

export type Lang = 'es' | 'it' | 'en';

export const translations: Record<Lang, Record<string, string>> = {
  es: {
    appName: 'Sa.To DiagnosticAI',
    appTagline: 'Diagnóstico inteligente para plantas industriales',
    home: 'Inicio',
    scan: 'Escanear',
    catalog: 'Catálogo',
    contact: 'Contacto',
    history: 'Historial',
    takPhoto: 'Tomar Foto',
    uploadPhoto: 'Subir Imagen',
    analyzeBtn: 'Analizar con IA',
    analyzing: 'Analizando...',
    diagnosisResult: 'Diagnóstico',
    possibleProblems: 'Problemas Detectados',
    severity: 'Severidad',
    recommendation: 'Recomendación',
    satoOffer: 'Solución Sa.To Green Energy',
    productName: 'Producto / Servicio',
    price: 'Precio Estimado',
    requestAssistance: 'Solicitar Asesoría Técnica',
    sendEmail: 'Enviar Email',
    whatsapp: 'WhatsApp',
    call: 'Llamar',
    catalogTitle: 'Catálogo de Equipos',
    filterAll: 'Todo',
    filterWater: 'Efluentes',
    filterBiogas: 'Biogas',
    filterEnergy: 'Energía',
    filterSolar: 'Solar',
    filterWind: 'Eólico',
    filterEthanol: 'Bioetanol',
    filterPyrolysis: 'Pirólisis',
    filterCompostaje: 'Compostaje',
    filterPumps: 'Bombas',
    contactForQuote: 'Contactar para presupuesto',
    settings: 'Ajustes',
    settingsTitle: 'Ajustes de la App',
    currency: 'Moneda',
    currencyLabel: 'Moneda de visualización',
    notes: 'Notas',
    addNote: 'Agregar nota manual...',
    saveNote: 'Guardar',
    notificationCritical: 'Problema crítico detectado',
    notifPermission: 'Activa notificaciones para alertas críticas',
    contactTitle: 'Contacto Sa.To Green Energy',
    contactSubtitle: 'Nuestro equipo está listo para asesorarte',
    ceo: 'CEO / Gerencia',
    projectManager: 'Project & Process Manager',
    email: 'Email Corporativo',
    historyTitle: 'Historial de Análisis',
    noHistory: 'Sin análisis previos',
    high: 'Alta',
    medium: 'Media',
    low: 'Baja',
    dragDrop: 'Arrastra una imagen aquí o haz clic para subir',
    supported: 'Soportado: JPG, PNG, WEBP',
    newScan: 'Nuevo Análisis',
    component: 'Componente',
    system: 'Sistema',
    detected: 'Detectado',
    usd: 'USD',
    consultRequired: 'Consultar',
    selectLang: 'Idioma',
    heroTitle: 'Diagnóstico Industrial con IA',
    heroSub: 'Fotografía cualquier equipo y obtén diagnóstico instantáneo con precios Sa.To',
    startScan: 'Iniciar Análisis',
    viewCatalog: 'Ver Catálogo',
    features: 'Capacidades',
    f1: 'Análisis IA de Imagen',
    f1d: 'Detecta fallos, desgaste y anomalías en equipos industriales',
    f2: 'Diagnóstico Multi-Planta',
    f2d: 'Cubre PTAR, Biogas, CHP, Solar, Eólico, Bioetanol y Pirólisis',
    f3: 'Precios en Tiempo Real',
    f3d: 'Listado de productos y servicios Sa.To actualizados',
    f4: 'Soporte Directo',
    f4d: 'Conexión inmediata con el equipo técnico Sa.To',
    date: 'Fecha',
    confidence: 'Confianza',
    viewDetail: 'Ver Detalle',
    imagePreview: 'Vista Previa',
    howItWorks: 'Cómo Funciona',
    step1: 'Fotografía el equipo',
    step1d: 'Usa la cámara o sube una imagen del equipo o componente a diagnosticar',
    step2: 'Análisis con IA',
    step2d: 'Nuestra IA identifica el componente y detecta posibles fallas o problemas',
    step3: 'Diagnóstico + Precios',
    step3d: 'Recibe el diagnóstico detallado con soluciones y precios Sa.To',
    step4: 'Solicita Asesoría',
    step4d: 'Conecta directamente con nuestro equipo técnico para resolver el problema',
    close: 'Cerrar',
    equipDetail: 'Detalle del Equipo',
    estPrice: 'Precio Estimado',
    availability: 'Disponibilidad',
    available: 'Disponible',
    leadTime: 'Tiempo de Entrega',
    days: 'días',
    requestQuote: 'Solicitar Cotización',
    emailSent: '¡Email preparado! Se abrirá tu cliente de correo.',
    msgBody: 'Estimado equipo Sa.To Green Energy,\n\nHe utilizado la app de diagnóstico y necesito asesoría técnica para el siguiente equipo/problema:\n\n[DESCRIBIR EQUIPO Y PROBLEMA]\n\nPor favor, contáctenme para coordinar una visita técnica.\n\nGracias.',
    subjectEmail: 'Solicitud de Asesoría Técnica - App DiagnosticAI',
    plantType: 'Tipo de Planta',
    equipmentType: 'Tipo de Equipo',
    satoSolution: 'Solución Sa.To',
  },
  it: {
    appName: 'Sa.To DiagnosticAI',
    appTagline: 'Diagnosi intelligente per impianti industriali',
    home: 'Home',
    scan: 'Scansiona',
    catalog: 'Catalogo',
    contact: 'Contatto',
    history: 'Cronologia',
    takPhoto: 'Scatta Foto',
    uploadPhoto: 'Carica Immagine',
    analyzeBtn: 'Analizza con IA',
    analyzing: 'Analisi in corso...',
    diagnosisResult: 'Diagnosi',
    possibleProblems: 'Problemi Rilevati',
    severity: 'Gravità',
    recommendation: 'Raccomandazione',
    satoOffer: 'Soluzione Sa.To Green Energy',
    productName: 'Prodotto / Servizio',
    price: 'Prezzo Stimato',
    requestAssistance: 'Richiedi Consulenza Tecnica',
    sendEmail: 'Invia Email',
    whatsapp: 'WhatsApp',
    call: 'Chiama',
    catalogTitle: 'Catalogo Apparecchiature',
    filterAll: 'Tutto',
    filterWater: 'Acque Reflue',
    filterBiogas: 'Biogas',
    filterEnergy: 'Energia',
    filterSolar: 'Solare',
    filterWind: 'Eolico',
    filterEthanol: 'Bioetanolo',
    filterPyrolysis: 'Pirolisi',
    filterCompostaje: 'Compostaggio',
    filterPumps: 'Pompe',
    contactForQuote: 'Contatta per preventivo',
    settings: 'Impostazioni',
    settingsTitle: 'Impostazioni App',
    currency: 'Valuta',
    currencyLabel: 'Valuta di visualizzazione',
    notes: 'Note',
    addNote: 'Aggiungi nota manuale...',
    saveNote: 'Salva',
    notificationCritical: 'Problema critico rilevato',
    notifPermission: 'Attiva notifiche per avvisi critici',
    contactTitle: 'Contatto Sa.To Green Energy',
    contactSubtitle: 'Il nostro team è pronto a supportarti',
    ceo: 'CEO / Direzione',
    projectManager: 'Project & Process Manager',
    email: 'Email Aziendale',
    historyTitle: 'Cronologia Analisi',
    noHistory: 'Nessuna analisi precedente',
    high: 'Alta',
    medium: 'Media',
    low: 'Bassa',
    dragDrop: 'Trascina un\'immagine qui o clicca per caricare',
    supported: 'Supportati: JPG, PNG, WEBP',
    newScan: 'Nuova Analisi',
    component: 'Componente',
    system: 'Sistema',
    detected: 'Rilevato',
    usd: 'USD',
    consultRequired: 'Da Consultare',
    selectLang: 'Lingua',
    heroTitle: 'Diagnostica Industriale con IA',
    heroSub: 'Fotografa qualsiasi apparecchiatura e ottieni una diagnosi istantanea con prezzi Sa.To',
    startScan: 'Inizia Analisi',
    viewCatalog: 'Vedi Catalogo',
    features: 'Funzionalità',
    f1: 'Analisi IA dell\'Immagine',
    f1d: 'Rileva guasti, usura e anomalie nelle apparecchiature industriali',
    f2: 'Diagnosi Multi-Impianto',
    f2d: 'Copre WWTP, Biogas, CHP, Solare, Eolico, Bioetanolo e Pirolisi',
    f3: 'Prezzi in Tempo Reale',
    f3d: 'Listino prodotti e servizi Sa.To aggiornato',
    f4: 'Supporto Diretto',
    f4d: 'Connessione immediata con il team tecnico Sa.To',
    date: 'Data',
    confidence: 'Confidenza',
    viewDetail: 'Vedi Dettaglio',
    imagePreview: 'Anteprima',
    howItWorks: 'Come Funziona',
    step1: 'Fotografa l\'apparecchiatura',
    step1d: 'Usa la fotocamera o carica un\'immagine del componente da diagnosticare',
    step2: 'Analisi con IA',
    step2d: 'La nostra IA identifica il componente e rileva possibili guasti o problemi',
    step3: 'Diagnosi + Prezzi',
    step3d: 'Ricevi la diagnosi dettagliata con soluzioni e prezzi Sa.To',
    step4: 'Richiedi Consulenza',
    step4d: 'Connettiti direttamente con il nostro team tecnico per risolvere il problema',
    close: 'Chiudi',
    equipDetail: 'Dettaglio Apparecchiatura',
    estPrice: 'Prezzo Stimato',
    availability: 'Disponibilità',
    available: 'Disponibile',
    leadTime: 'Tempi di Consegna',
    days: 'giorni',
    requestQuote: 'Richiedi Preventivo',
    emailSent: 'Email pronta! Si aprirà il tuo client di posta.',
    msgBody: 'Gentile team Sa.To Green Energy,\n\nHo utilizzato l\'app di diagnostica e ho bisogno di consulenza tecnica per la seguente apparecchiatura/problema:\n\n[DESCRIVERE APPARECCHIATURA E PROBLEMA]\n\nVi prego di contattarmi per organizzare un sopralluogo tecnico.\n\nGrazie.',
    subjectEmail: 'Richiesta Consulenza Tecnica - App DiagnosticAI',
    plantType: 'Tipo di Impianto',
    equipmentType: 'Tipo di Apparecchiatura',
    satoSolution: 'Soluzione Sa.To',
  },
  en: {
    appName: 'Sa.To DiagnosticAI',
    appTagline: 'Smart diagnostics for industrial plants',
    home: 'Home',
    scan: 'Scan',
    catalog: 'Catalog',
    contact: 'Contact',
    history: 'History',
    takPhoto: 'Take Photo',
    uploadPhoto: 'Upload Image',
    analyzeBtn: 'Analyze with AI',
    analyzing: 'Analyzing...',
    diagnosisResult: 'Diagnosis',
    possibleProblems: 'Detected Issues',
    severity: 'Severity',
    recommendation: 'Recommendation',
    satoOffer: 'Sa.To Green Energy Solution',
    productName: 'Product / Service',
    price: 'Estimated Price',
    requestAssistance: 'Request Technical Support',
    sendEmail: 'Send Email',
    whatsapp: 'WhatsApp',
    call: 'Call',
    catalogTitle: 'Equipment Catalog',
    filterAll: 'All',
    filterWater: 'Wastewater',
    filterBiogas: 'Biogas',
    filterEnergy: 'Energy',
    filterSolar: 'Solar',
    filterWind: 'Wind',
    filterEthanol: 'Bioethanol',
    filterPyrolysis: 'Pyrolysis',
    filterCompostaje: 'Composting',
    filterPumps: 'Pumps',
    contactForQuote: 'Contact for quote',
    settings: 'Settings',
    settingsTitle: 'App Settings',
    currency: 'Currency',
    currencyLabel: 'Display currency',
    notes: 'Notes',
    addNote: 'Add manual note...',
    saveNote: 'Save',
    notificationCritical: 'Critical issue detected',
    notifPermission: 'Enable notifications for critical alerts',
    contactTitle: 'Contact Sa.To Green Energy',
    contactSubtitle: 'Our team is ready to support you',
    ceo: 'CEO / Management',
    projectManager: 'Project & Process Manager',
    email: 'Corporate Email',
    historyTitle: 'Analysis History',
    noHistory: 'No previous analyses',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    dragDrop: 'Drag an image here or click to upload',
    supported: 'Supported: JPG, PNG, WEBP',
    newScan: 'New Scan',
    component: 'Component',
    system: 'System',
    detected: 'Detected',
    usd: 'USD',
    consultRequired: 'Consult Required',
    selectLang: 'Language',
    heroTitle: 'Industrial AI Diagnostics',
    heroSub: 'Photograph any equipment and get instant diagnosis with Sa.To pricing',
    startScan: 'Start Analysis',
    viewCatalog: 'View Catalog',
    features: 'Capabilities',
    f1: 'AI Image Analysis',
    f1d: 'Detects failures, wear and anomalies in industrial equipment',
    f2: 'Multi-Plant Diagnostics',
    f2d: 'Covers WWTP, Biogas, CHP, Solar, Wind, Bioethanol and Pyrolysis',
    f3: 'Real-Time Pricing',
    f3d: 'Updated Sa.To product and service listing',
    f4: 'Direct Support',
    f4d: 'Immediate connection with the Sa.To technical team',
    date: 'Date',
    confidence: 'Confidence',
    viewDetail: 'View Detail',
    imagePreview: 'Preview',
    howItWorks: 'How It Works',
    step1: 'Photograph the equipment',
    step1d: 'Use the camera or upload an image of the component to diagnose',
    step2: 'AI Analysis',
    step2d: 'Our AI identifies the component and detects possible failures or problems',
    step3: 'Diagnosis + Pricing',
    step3d: 'Receive the detailed diagnosis with Sa.To solutions and prices',
    step4: 'Request Support',
    step4d: 'Connect directly with our technical team to solve the problem',
    close: 'Close',
    equipDetail: 'Equipment Detail',
    estPrice: 'Estimated Price',
    availability: 'Availability',
    available: 'Available',
    leadTime: 'Lead Time',
    days: 'days',
    requestQuote: 'Request Quote',
    emailSent: 'Email ready! Your mail client will open.',
    msgBody: 'Dear Sa.To Green Energy team,\n\nI have used the diagnostic app and need technical support for the following equipment/problem:\n\n[DESCRIBE EQUIPMENT AND PROBLEM]\n\nPlease contact me to arrange a technical visit.\n\nThank you.',
    subjectEmail: 'Technical Support Request - DiagnosticAI App',
    plantType: 'Plant Type',
    equipmentType: 'Equipment Type',
    satoSolution: 'Sa.To Solution',
  },
};

const LanguageContext = createContext<{
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}>({ lang: 'es', setLang: () => {}, t: (k) => k });

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLang] = useState<Lang>('es');
  const t = (key: string) => translations[lang][key] || key;
  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
};

export const useLang = () => useContext(LanguageContext);
